"use client";
import { useEffect, useState } from "react";
import { AlertTriangle, BarChart3, Beaker, CheckCircle2, Users } from "lucide-react";
type Dashboard = { volume:{exercises:number;attempts:number;uniqueUsers:number}; quality:{healthy:number;monitor:number;needsReview:number;highRisk:number;insufficientData:number}; alerts:Array<{id:string;alert_type:string;severity:string;explanation:string;recommendation:string}>; experiments:Array<{id:string;name:string;status:string;primary_metric:string}> };
export function AdminAnalyticsDashboard() {
  const [data,setData]=useState<Dashboard|null>(null); const [error,setError]=useState("");
  useEffect(()=>{fetch("/api/admin/training/analytics",{cache:"no-store"}).then(async response=>{if(!response.ok) throw new Error("No se pudo cargar la analítica."); const body=await response.json() as {data:Dashboard}; setData(body.data);}).catch((cause:Error)=>setError(cause.message));},[]);
  if(error) return <p className="rounded-[8px] border border-red-200 bg-red-50 p-4 text-red-800">{error}</p>;
  if(!data) return <div className="h-40 animate-pulse rounded-[8px] border border-slate-200 bg-white" aria-label="Cargando analítica"/>;
  const cards=[["Ejercicios medidos",data.volume.exercises,BarChart3],["Intentos válidos",data.volume.attempts,CheckCircle2],["Usuarios observados",data.volume.uniqueUsers,Users],["Alertas activas",data.alerts.length,AlertTriangle]] as const;
  const labels:Record<string,string>={healthy:"Saludable",monitor:"En observación",needsReview:"Requiere revisión",highRisk:"Alto riesgo",insufficientData:"Sin evidencia"};
  return <><header className="border-b border-slate-200 pb-5"><p className="text-sm font-bold uppercase text-violet-700">Training</p><h1 className="mt-1 text-3xl font-black">Analítica pedagógica</h1><p className="mt-1 text-slate-600">Evidencia agregada para mejorar aprendizaje y contenido, sin exponer respuestas privadas.</p></header><section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon])=><article className="rounded-[8px] border border-slate-200 bg-white p-5" key={label}><Icon className="text-violet-700" size={21}/><p className="mt-4 text-3xl font-black">{value}</p><p className="text-sm text-slate-600">{label}</p></article>)}</section><section className="mt-6 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><article className="rounded-[8px] border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Estado de calidad</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5">{Object.entries(data.quality).map(([key,value])=><div className="border-l-2 border-violet-300 pl-3" key={key}><strong className="text-2xl">{value}</strong><p className="text-xs text-slate-500">{labels[key]}</p></div>)}</div></article><article className="rounded-[8px] border border-slate-200 bg-white p-5"><h2 className="flex items-center gap-2 text-xl font-black"><Beaker size={20}/> Experimentos activos</h2><p className="mt-4 text-sm text-slate-600">{data.experiments.length?`${data.experiments.length} experimentos controlados en curso.`:"No hay experimentos activos."}</p></article></section><section className="mt-5 rounded-[8px] border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Alertas que requieren atención</h2>{data.alerts.length?<div className="mt-4 divide-y divide-slate-100">{data.alerts.map(alert=><div className="py-4" key={alert.id}><strong>{alert.alert_type.replaceAll("_"," ")}</strong><p className="mt-2 text-sm text-slate-700">{alert.explanation}</p><p className="mt-1 text-sm text-slate-500">Siguiente paso: {alert.recommendation}</p></div>)}</div>:<p className="mt-3 text-slate-500">No hay alertas abiertas con evidencia suficiente.</p>}</section></>;
}
