import Link from "next/link";
import { ArrowRight, Clock3 } from "lucide-react";
import { TrainingIcon, TrainingProgressBar, TrainingStatusChip } from "@/components/training/TrainingPrimitives";
import type { TrainingActivity } from "@/types/training";

export function ContinueTrainingCard({ activity }: { activity: TrainingActivity }) {
  if (activity.status === "loading") return <article aria-label="Cargando entrenamiento" className="animate-pulse rounded-[8px] border border-slate-950/[0.08] bg-white p-5 motion-reduce:animate-none"><div className="h-6 w-2/3 rounded bg-slate-100" /><div className="mt-3 h-4 w-1/2 rounded bg-slate-100" /><div className="mt-8 h-1.5 rounded bg-slate-100" /></article>;
  if (activity.status === "error") return <article className="rounded-[8px] border border-rose-200 bg-rose-50 p-5"><TrainingStatusChip status="error" /><h3 className="mt-3 font-black text-slate-950">No pudimos cargar este entrenamiento</h3><p className="mt-1 text-sm text-slate-600">Vuelve a intentarlo dentro de unos minutos.</p></article>;
  const isLocked = activity.status === "locked";
  return <article className="rounded-[8px] border border-slate-950/[0.08] bg-white p-5 transition-colors hover:border-violet-200 motion-reduce:transition-none"><div className="flex items-start gap-4"><span className="grid h-16 w-16 shrink-0 place-items-center rounded-[8px] bg-violet-50 text-violet-700"><TrainingIcon icon={activity.icon} size={29} /></span><div className="min-w-0 flex-1"><h3 className="font-black text-slate-950">{activity.title}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{activity.description}</p><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><TrainingStatusChip status={activity.status} /><span className="text-xs font-semibold text-slate-500">{activity.progressLabel}</span></div></div></div><div className="mt-4"><TrainingProgressBar label={activity.title} value={activity.progress} /></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><span className="inline-flex items-center gap-2 text-xs font-semibold text-slate-500"><Clock3 size={15} />{activity.detail}</span>{isLocked ? <button className="min-h-10 rounded-[8px] bg-slate-200 px-4 text-sm font-bold text-slate-500" disabled type="button">Bloqueado</button> : <Link className="inline-flex min-h-10 items-center gap-2 rounded-[8px] bg-violet-700 px-4 text-sm font-bold text-white transition-colors hover:bg-violet-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-600 motion-reduce:transition-none" href={`/ejercicios?entrenamiento=${activity.id}`}>{activity.ctaLabel}<ArrowRight size={15} /></Link>}</div></article>;
}
