import OpenAI from "openai";
import type { SupabaseClient } from "@supabase/supabase-js";
import { serverEnv } from "@/lib/env";
import { getEffectiveSubscriptionForUser } from "@/lib/subscriptions/service";
import type { PlanKey } from "@/config/plans";

export type RoleplayLevel = "fundamentals"|"application"|"advanced";
export function roleplayEntitlement(plan:PlanKey,used:number){
  const paid=plan==="pro"||plan==="founder"; const unlimited=plan==="unlimited"; const limit=paid?serverEnv.TRAINING_ROLEPLAY_PRO_MONTHLY_LIMIT:unlimited?null:0;
  return { canStart:unlimited||(paid&&used<(limit??0)), monthlyLimit:limit, remaining:limit===null?null:Math.max(0,limit-used), levels:unlimited?["fundamentals","application","advanced"] as RoleplayLevel[]:paid?["fundamentals","application"] as RoleplayLevel[]:[] as RoleplayLevel[], customScenarios:unlimited&&serverEnv.TRAINING_ROLEPLAY_CUSTOM_SCENARIOS_ENABLED };
}

export class TrainingRoleplayService {
  constructor(private readonly db:SupabaseClient){}
  private month(){return new Date(Date.UTC(new Date().getUTCFullYear(),new Date().getUTCMonth(),1)).toISOString().slice(0,10);}
  async access(userId:string){const [subscription,{count}]=await Promise.all([getEffectiveSubscriptionForUser(userId),this.db.from("training_roleplay_usage").select("id",{count:"exact",head:true}).eq("user_id",userId).eq("usage_month",this.month())]); return {plan:subscription.plan,...roleplayEntitlement(subscription.plan,count??0)};}
  async catalog(userId:string){const [access,{data}]=await Promise.all([this.access(userId),this.db.from("training_roleplay_scenarios").select("id,slug,title,description,category,level,learner_goal").eq("is_active",true).order("level")]); return {access,alternatives:{deterministicExercisesHref:"/ejercicios",unlimitedPlanHref:"/planes"},scenarios:(data??[]).map(item=>({...item,canStart:access.canStart&&access.levels.includes(item.level as RoleplayLevel)}))};}
  async start(userId:string,input:{scenarioId?:string;customScenario?:{title:string;character:string;goal:string;openingMessage:string}}){
    if(!serverEnv.TRAINING_ROLEPLAY_ENABLED) throw new Error("ROLEPLAY_DISABLED"); const access=await this.access(userId); if(!access.canStart) throw new Error(access.plan==="free"?"PLAN_REQUIRED":"MONTHLY_LIMIT_REACHED");
    const activeSince=new Date(Date.now()-serverEnv.TRAINING_ROLEPLAY_MAX_DURATION_SECONDS*1000).toISOString(); const {count:active}=await this.db.from("training_roleplay_sessions").select("id",{count:"exact",head:true}).eq("user_id",userId).in("status",["ready","active"]).gte("started_at",activeSince); if((active??0)>=serverEnv.TRAINING_ROLEPLAY_MAX_CONCURRENT) throw new Error("CONCURRENT_LIMIT");
    let scenario:null|{id:string;level:string;opening_message:string}=null; if(input.scenarioId){const {data}=await this.db.from("training_roleplay_scenarios").select("id,level,opening_message").eq("id",input.scenarioId).eq("is_active",true).maybeSingle(); scenario=data; if(!scenario) throw new Error("SCENARIO_NOT_FOUND"); if(!access.levels.includes(scenario.level as RoleplayLevel)) throw new Error("DIFFICULTY_LOCKED");} else if(!access.customScenarios||!input.customScenario) throw new Error("CUSTOM_SCENARIO_LOCKED");
    const opening=scenario?.opening_message??input.customScenario!.openingMessage; const {data:session,error}=await this.db.from("training_roleplay_sessions").insert({user_id:userId,scenario_id:scenario?.id??null,custom_scenario:scenario?null:input.customScenario,plan_snapshot:access.plan,status:"ready"}).select("id,created_at").single(); if(error||!session) throw new Error("SESSION_CREATE_FAILED"); await this.db.from("training_roleplay_messages").insert({session_id:session.id,user_id:userId,role:"character",content:opening,turn_number:0}); return {sessionId:session.id,openingMessage:opening,access:{remaining:access.remaining}};
  }
  async turn(userId:string,sessionId:string,input:{clientTurnId:string;message:string}):Promise<{reply:string|undefined;idempotent:boolean;turn?:number;limits?:{maxTurns:number;maxDurationSeconds:number}}>{
    const {data:duplicate}=await this.db.from("training_roleplay_messages").select("turn_number").eq("user_id",userId).eq("client_turn_id",input.clientTurnId).maybeSingle(); if(duplicate){const {data:reply}=await this.db.from("training_roleplay_messages").select("content").eq("session_id",sessionId).eq("role","character").eq("turn_number",duplicate.turn_number).maybeSingle(); return {reply:reply?.content,idempotent:true};}
    const {data:session}=await this.db.from("training_roleplay_sessions").select("*,training_roleplay_scenarios(*)").eq("id",sessionId).eq("user_id",userId).maybeSingle(); if(!session||!["ready","active"].includes(session.status)) throw new Error("SESSION_NOT_ACTIVE"); const elapsed=(Date.now()-new Date(session.started_at).getTime())/1000; if(elapsed>serverEnv.TRAINING_ROLEPLAY_MAX_DURATION_SECONDS) throw new Error("SESSION_EXPIRED"); if(session.turn_count>=serverEnv.TRAINING_ROLEPLAY_MAX_TURNS) throw new Error("TURN_LIMIT");
    const access=await this.access(userId); if(!session.quota_consumed_at&&!access.canStart) throw new Error("MONTHLY_LIMIT_REACHED"); const since=new Date(Date.now()-60_000).toISOString(); const {count:recent}=await this.db.from("training_roleplay_messages").select("id",{count:"exact",head:true}).eq("user_id",userId).eq("role","user").gte("created_at",since); if((recent??0)>=serverEnv.TRAINING_ROLEPLAY_RATE_LIMIT_PER_MINUTE) throw new Error("RATE_LIMITED");
    const today=new Date().toISOString().slice(0,10); const {count:daily}=await this.db.from("training_roleplay_usage").select("id",{count:"exact",head:true}).eq("user_id",userId).gte("consumed_at",`${today}T00:00:00.000Z`); if((daily??0)>=serverEnv.TRAINING_ROLEPLAY_DAILY_EMERGENCY_LIMIT) throw new Error("DAILY_SAFETY_LIMIT");
    if(!serverEnv.OPENAI_API_KEY||!serverEnv.OPENAI_CHAT_MODEL) throw new Error("PROVIDER_UNAVAILABLE"); const scenario=Array.isArray(session.training_roleplay_scenarios)?session.training_roleplay_scenarios[0]:session.training_roleplay_scenarios; const custom=session.custom_scenario as Record<string,string>|null; const {data:history}=await this.db.from("training_roleplay_messages").select("role,content").eq("session_id",sessionId).order("created_at").limit(30);
    const response=await new OpenAI({apiKey:serverEnv.OPENAI_API_KEY}).responses.create({model:serverEnv.OPENAI_CHAT_MODEL,input:[{role:"system",content:`Eres ${scenario?.character_name??custom?.character}, un personaje de práctica. Mantén el rol. Objetivo del alumno: ${scenario?.learner_goal??custom?.goal}. Responde en español, breve y realista. No des la solución ni salgas del escenario.`},...(history??[]).map(item=>({role:item.role==="user"?"user" as const:"assistant" as const,content:item.content})),{role:"user",content:input.message}],max_output_tokens:400}); const reply=response.output_text.trim(); if(!reply) throw new Error("PROVIDER_EMPTY_RESPONSE"); const turn=session.turn_count+1;
    const {error:userError}=await this.db.from("training_roleplay_messages").insert({session_id:sessionId,user_id:userId,client_turn_id:input.clientTurnId,role:"user",content:input.message,turn_number:turn}); if(userError?.code==="23505"){const {data:savedUser}=await this.db.from("training_roleplay_messages").select("turn_number").eq("user_id",userId).eq("client_turn_id",input.clientTurnId).maybeSingle();const {data:savedReply}=await this.db.from("training_roleplay_messages").select("content").eq("session_id",sessionId).eq("role","character").eq("turn_number",savedUser?.turn_number??-1).maybeSingle();return {reply:savedReply?.content,idempotent:true};} if(userError) throw new Error("MESSAGE_SAVE_FAILED"); await this.db.from("training_roleplay_messages").insert({session_id:sessionId,user_id:userId,role:"character",content:reply,turn_number:turn,provider:"openai",model:serverEnv.OPENAI_CHAT_MODEL}); await this.db.from("training_roleplay_sessions").update({status:"active",turn_count:turn,first_valid_user_turn_at:session.first_valid_user_turn_at??new Date().toISOString(),provider_responded_at:new Date().toISOString(),last_activity_at:new Date().toISOString()}).eq("id",sessionId);
    if(!session.quota_consumed_at){const {error}=await this.db.rpc("consume_training_roleplay_quota",{p_session_id:sessionId,p_user_id:userId,p_monthly_limit:serverEnv.TRAINING_ROLEPLAY_PRO_MONTHLY_LIMIT}); if(error){await this.db.from("training_roleplay_messages").delete().eq("session_id",sessionId).eq("turn_number",turn);await this.db.from("training_roleplay_sessions").update({status:"failed"}).eq("id",sessionId);throw new Error(error.message.includes("monthly_limit")?"MONTHLY_LIMIT_REACHED":"QUOTA_CONSUME_FAILED");}}
    return {reply,idempotent:false,turn,limits:{maxTurns:serverEnv.TRAINING_ROLEPLAY_MAX_TURNS,maxDurationSeconds:serverEnv.TRAINING_ROLEPLAY_MAX_DURATION_SECONDS}};
  }
}
