create extension if not exists pgcrypto;

create table public.training_categories(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,description text,icon text,sort_order integer not null default 0,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.training_skills(id uuid primary key default gen_random_uuid(),category_id uuid not null references public.training_categories on delete cascade,slug text unique not null,name text not null,description text,initial_difficulty text not null default 'intermediate' check(initial_difficulty in('beginner','intermediate','advanced')),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.training_concepts(id uuid primary key default gen_random_uuid(),skill_id uuid not null references public.training_skills on delete cascade,slug text unique not null,name text not null,description text,difficulty text not null check(difficulty in('beginner','intermediate','advanced')),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.training_exercises(id uuid primary key default gen_random_uuid(),skill_id uuid not null references public.training_skills,concept_id uuid not null references public.training_concepts,type text not null check(type in('single_choice','multiple_choice','true_false','ordering','flashcard','scenario')),title text,prompt text not null,instruction text not null,difficulty text not null check(difficulty in('beginner','intermediate','advanced')),estimated_seconds integer check(estimated_seconds>0),hint text,explanation text not null,content jsonb not null,status text not null default 'draft' check(status in('draft','published','archived')),version integer not null default 1 check(version>0),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.training_exercise_evaluation_rules(exercise_id uuid primary key references public.training_exercises on delete cascade,evaluation_config jsonb not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.training_exercise_books(exercise_id uuid references public.training_exercises on delete cascade,book_id uuid references public.books on delete cascade,concept_reference text,is_primary boolean not null default false,created_at timestamptz not null default now(),primary key(exercise_id,book_id));
create table public.training_templates(id uuid primary key default gen_random_uuid(),slug text unique not null,title text not null,description text,category_id uuid not null references public.training_categories,difficulty text not null check(difficulty in('beginner','intermediate','advanced')),estimated_minutes integer not null check(estimated_minutes>0),midpoint_enabled boolean not null default true,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.training_template_exercises(template_id uuid references public.training_templates on delete cascade,exercise_id uuid references public.training_exercises on delete restrict,position integer not null check(position>0),is_final_challenge boolean not null default false,created_at timestamptz not null default now(),primary key(template_id,exercise_id),unique(template_id,position));
create table public.training_sessions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,template_id uuid not null references public.training_templates,title text not null,status text not null default 'not_started' check(status in('not_started','in_progress','completed','abandoned')),current_exercise_index integer not null default 0 check(current_exercise_index>=0),total_exercises integer not null check(total_exercises>0),estimated_minutes integer,started_at timestamptz,updated_at timestamptz not null default now(),completed_at timestamptz,abandoned_at timestamptz,result_summary jsonb,created_at timestamptz not null default now());
create table public.training_session_exercises(id uuid primary key default gen_random_uuid(),session_id uuid not null references public.training_sessions on delete cascade,exercise_id uuid not null references public.training_exercises,position integer not null check(position>0),exercise_snapshot jsonb not null,created_at timestamptz not null default now(),unique(session_id,position),unique(session_id,exercise_id));
create table public.training_answers(id uuid primary key default gen_random_uuid(),client_attempt_id uuid not null,user_id uuid not null references auth.users on delete cascade,session_id uuid not null references public.training_sessions on delete cascade,session_exercise_id uuid not null references public.training_session_exercises on delete cascade,answer jsonb not null,attempt_number integer not null check(attempt_number>0),is_correct boolean,score numeric not null default 0 check(score between 0 and 100),hints_used integer not null default 0 check(hints_used>=0),response_time_ms integer check(response_time_ms>=0),evaluation_details jsonb,created_at timestamptz not null default now(),unique(user_id,client_attempt_id));
create table public.user_skill_mastery(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,skill_id uuid not null references public.training_skills on delete cascade,mastery_score numeric not null default 0 check(mastery_score between 0 and 100),status text not null default 'discovering' check(status in('discovering','developing','competent','mastered','needs_review')),total_attempts integer not null default 0,correct_attempts integer not null default 0,last_practiced_at timestamptz,last_score numeric,current_streak integer not null default 0,next_review_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,skill_id));
create table public.user_concept_mastery(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,concept_id uuid not null references public.training_concepts on delete cascade,mastery_score numeric not null default 0 check(mastery_score between 0 and 100),attempts integer not null default 0,correct_attempts integer not null default 0,hints_used integer not null default 0,last_practiced_at timestamptz,next_review_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,concept_id));
create table public.training_review_schedule(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,skill_id uuid references public.training_skills,concept_id uuid references public.training_concepts,source_answer_id uuid references public.training_answers on delete set null,scheduled_for timestamptz not null,priority integer not null default 0,status text not null default 'pending' check(status in('pending','completed','skipped','cancelled')),completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.user_training_streaks(user_id uuid primary key references auth.users on delete cascade,current_streak integer not null default 0,longest_streak integer not null default 0,last_training_date date,weekly_activity jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create index training_sessions_user_status_idx on public.training_sessions(user_id,status); create index training_sessions_user_updated_idx on public.training_sessions(user_id,updated_at desc); create index training_answers_session_idx on public.training_answers(session_id); create index training_answers_user_created_idx on public.training_answers(user_id,created_at desc); create index skill_mastery_user_idx on public.user_skill_mastery(user_id); create index skill_mastery_review_idx on public.user_skill_mastery(user_id,next_review_at); create index concept_mastery_review_idx on public.user_concept_mastery(user_id,next_review_at); create index training_reviews_due_idx on public.training_review_schedule(user_id,status,scheduled_for); create index session_exercises_position_idx on public.training_session_exercises(session_id,position); create index template_exercises_position_idx on public.training_template_exercises(template_id,position);

alter table public.training_categories enable row level security; alter table public.training_skills enable row level security; alter table public.training_concepts enable row level security; alter table public.training_exercises enable row level security; alter table public.training_exercise_evaluation_rules enable row level security; alter table public.training_exercise_books enable row level security; alter table public.training_templates enable row level security; alter table public.training_template_exercises enable row level security; alter table public.training_sessions enable row level security; alter table public.training_session_exercises enable row level security; alter table public.training_answers enable row level security; alter table public.user_skill_mastery enable row level security; alter table public.user_concept_mastery enable row level security; alter table public.training_review_schedule enable row level security; alter table public.user_training_streaks enable row level security;
create policy training_categories_read on public.training_categories for select to authenticated using(is_active); create policy training_skills_read on public.training_skills for select to authenticated using(is_active); create policy training_concepts_read on public.training_concepts for select to authenticated using(is_active); create policy training_exercises_read on public.training_exercises for select to authenticated using(status='published'); create policy training_templates_read on public.training_templates for select to authenticated using(is_active); create policy training_template_exercises_read on public.training_template_exercises for select to authenticated using(true); create policy training_exercise_books_read on public.training_exercise_books for select to authenticated using(true);
create policy training_sessions_own on public.training_sessions for select to authenticated using(user_id=auth.uid()); create policy training_sessions_update_own on public.training_sessions for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy session_exercises_own on public.training_session_exercises for select to authenticated using(exists(select 1 from public.training_sessions s where s.id=session_id and s.user_id=auth.uid())); create policy answers_own_read on public.training_answers for select to authenticated using(user_id=auth.uid()); create policy skill_mastery_own_read on public.user_skill_mastery for select to authenticated using(user_id=auth.uid()); create policy concept_mastery_own_read on public.user_concept_mastery for select to authenticated using(user_id=auth.uid()); create policy reviews_own on public.training_review_schedule for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy streak_own_read on public.user_training_streaks for select to authenticated using(user_id=auth.uid());

create or replace function public.create_training_session(p_template_id uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid(); v_id uuid; v_count int; begin if v_user is null then raise exception 'unauthenticated'; end if; select count(*) into v_count from training_template_exercises where template_id=p_template_id; if v_count=0 then raise exception 'template_empty'; end if; insert into training_sessions(user_id,template_id,title,total_exercises,estimated_minutes) select v_user,id,title,v_count,estimated_minutes from training_templates where id=p_template_id and is_active returning id into v_id; if v_id is null then raise exception 'template_not_found'; end if; insert into training_session_exercises(session_id,exercise_id,position,exercise_snapshot) select v_id,e.id,te.position,jsonb_build_object('id',e.id,'type',e.type,'title',e.title,'prompt',e.prompt,'instruction',e.instruction,'difficulty',e.difficulty,'estimatedSeconds',e.estimated_seconds,'hint',e.hint,'explanation',e.explanation,'content',e.content,'skillId',e.skill_id,'conceptId',e.concept_id) from training_template_exercises te join training_exercises e on e.id=te.exercise_id where te.template_id=p_template_id order by te.position; return v_id; end $$;
grant execute on function public.create_training_session(uuid) to authenticated;
