create or replace function public.apply_training_mastery_and_reviews(p_session_id uuid,p_user_id uuid) returns void language plpgsql security definer set search_path=public as $$ begin
insert into user_skill_mastery(user_id,skill_id,mastery_score,status,total_attempts,correct_attempts,last_practiced_at,last_score,next_review_at)
select p_user_id,e.skill_id,round(avg(a.score)*.25,2),case when avg(a.score)*.25>=70 then 'competent' when avg(a.score)*.25>=40 then 'developing' else 'discovering' end,count(*),count(*) filter(where a.is_correct),now(),avg(a.score),min(now()+case when not a.is_correct then interval '1 day' when a.attempt_number>1 then interval '2 days' when a.hints_used>0 then interval '3 days' when e.difficulty='advanced' then interval '10 days' else interval '7 days' end)
from training_answers a join training_session_exercises se on se.id=a.session_exercise_id join training_exercises e on e.id=se.exercise_id where a.session_id=p_session_id and a.user_id=p_user_id group by e.skill_id
on conflict(user_id,skill_id) do update set mastery_score=least(100,greatest(0,user_skill_mastery.mastery_score*.75+excluded.last_score*.25)),status=case when user_skill_mastery.mastery_score*.75+excluded.last_score*.25>=85 then 'mastered' when user_skill_mastery.mastery_score*.75+excluded.last_score*.25>=70 then 'competent' when user_skill_mastery.mastery_score*.75+excluded.last_score*.25>=40 then 'developing' else 'discovering' end,total_attempts=user_skill_mastery.total_attempts+excluded.total_attempts,correct_attempts=user_skill_mastery.correct_attempts+excluded.correct_attempts,last_practiced_at=now(),last_score=excluded.last_score,next_review_at=excluded.next_review_at,updated_at=now();
insert into user_concept_mastery(user_id,concept_id,mastery_score,attempts,correct_attempts,hints_used,last_practiced_at,next_review_at)
select p_user_id,e.concept_id,round(avg(a.score)*.25,2),count(*),count(*) filter(where a.is_correct),sum(a.hints_used),now(),min(now()+case when not a.is_correct then interval '1 day' when a.attempt_number>1 then interval '2 days' when a.hints_used>0 then interval '3 days' else interval '7 days' end) from training_answers a join training_session_exercises se on se.id=a.session_exercise_id join training_exercises e on e.id=se.exercise_id where a.session_id=p_session_id and a.user_id=p_user_id group by e.concept_id on conflict(user_id,concept_id) do update set mastery_score=least(100,greatest(0,user_concept_mastery.mastery_score*.75+excluded.mastery_score)),attempts=user_concept_mastery.attempts+excluded.attempts,correct_attempts=user_concept_mastery.correct_attempts+excluded.correct_attempts,hints_used=user_concept_mastery.hints_used+excluded.hints_used,last_practiced_at=now(),next_review_at=excluded.next_review_at,updated_at=now();
insert into training_review_schedule(user_id,skill_id,concept_id,source_answer_id,scheduled_for,priority)
select p_user_id,e.skill_id,e.concept_id,a.id,now()+case when not a.is_correct then interval '1 day' when a.attempt_number>1 then interval '2 days' when a.hints_used>0 then interval '3 days' when e.difficulty='advanced' then interval '10 days' else interval '7 days' end,case when not a.is_correct then 10 else 0 end from training_answers a join training_session_exercises se on se.id=a.session_exercise_id join training_exercises e on e.id=se.exercise_id where a.session_id=p_session_id and a.user_id=p_user_id;
end $$;

create or replace function public.complete_training_session(p_session_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid(); v_summary jsonb; v_today date:=current_date; begin if v_user is null then raise exception 'unauthenticated'; end if; if exists(select 1 from training_sessions where id=p_session_id and user_id=v_user and status='completed') then return (select result_summary from training_sessions where id=p_session_id); end if; if not exists(select 1 from training_sessions where id=p_session_id and user_id=v_user) then raise exception 'session_forbidden'; end if; select jsonb_build_object('correctAnswers',count(*) filter(where is_correct),'incorrectAnswers',count(*) filter(where not is_correct),'score',coalesce(round(avg(score)),0),'completedAt',now()) into v_summary from (select distinct on(session_exercise_id) * from training_answers where session_id=p_session_id and user_id=v_user order by session_exercise_id,attempt_number desc)a; update training_sessions set status='completed',completed_at=now(),updated_at=now(),result_summary=v_summary where id=p_session_id and user_id=v_user and status<>'completed'; perform apply_training_mastery_and_reviews(p_session_id,v_user); insert into user_training_streaks(user_id,current_streak,longest_streak,last_training_date,weekly_activity) values(v_user,1,1,v_today,jsonb_build_object(v_today::text,true)) on conflict(user_id) do update set current_streak=case when user_training_streaks.last_training_date=v_today then user_training_streaks.current_streak when user_training_streaks.last_training_date=v_today-1 then user_training_streaks.current_streak+1 else 1 end,longest_streak=greatest(user_training_streaks.longest_streak,case when user_training_streaks.last_training_date=v_today-1 then user_training_streaks.current_streak+1 else 1 end),last_training_date=v_today,weekly_activity=user_training_streaks.weekly_activity||jsonb_build_object(v_today::text,true),updated_at=now(); return v_summary; end $$;
grant execute on function public.complete_training_session(uuid) to authenticated;
